[package]
name = "ferrous-opencc-compiler"
version = "0.3.0"
edition = "2024"
description = "Crate used to compile dictionary files into binary files"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
bincode = "2"
fst = "0"
zstd = "0.13"
